// Generated by generate_wrap_init.pl -- DO NOT MODIFY!

#define GLIBMM_INCLUDED_FROM_WRAP_INIT_CC
#include <glibmm.h>

// Disable the 'const' function attribute of the get_type() functions.
// GCC would optimize them out because we don't use the return value.
#undef G_GNUC_CONST
#define G_GNUC_CONST /* empty */

#include <glibmm/error.h>
#include <glibmm/object.h>
#include <tangent/gtkutil/mm/wrap_init.h>

// #include the widget headers so that we can call the get_type() static
// methods:
#include "panzoomarea.h"

extern "C" {
// Declarations of the *_get_type() functions:

GType gtk_panzoom_area_get_type(void);

// Declarations of the *_error_quark() functions:

}  // extern "C"

namespace Gtk {

// Declarations of the *_Class::wrap_new() methods, instead of including all the
// private headers:

class PanZoomArea_Class {
 public:
  static Glib::ObjectBase* wrap_new(GObject*);
};

void wrap_init() {
  // Register Error domains in the main namespace:

  // Map gtypes to gtkmm wrapper-creation functions:
  Glib::wrap_register(gtk_panzoom_area_get_type(),
                      &PanZoomArea_Class::wrap_new);

  // Register the gtkmm gtypes:
  PanZoomArea::get_type();

}  // wrap_init()

}  // namespace Gtk
